# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#
# $font = Sans
# $font = Monospace
$font = "Ndot55Caps"
# $font = "ndot55"
# $font = CaskaydiaMono Nerd Font
# $font = ndot 55
general {
    hide_cursor = false
    ignore_empty_input = true
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 2, 1, 0, 0
    animation = fadeIn, 2, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

# background {
#     # monitor = eDP-1
#     monitor =
#     path =  /home/dln/Wallpapers/nordic-obsession.png
#     blur_passes = 3
# }

background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 0.50)
    noise = 0.0017
    blur_size = 2
    blur_passes = 3
    vibrancy = 0.6448
    vibrancy_darkness = 1
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 94
    font_family = $font

    position = -30, -30
    halign = right
    valign = top
}

label {
    text = cmd[update:60000] /home/dln/.dotfiles/bin/days_since
    monitor =
    color = rgba(255,255,255,0.9)
    font_size = 18
    font_family = Ndot 55
    position = 0, 100
    halign = center
    valign = bottom
    shadow_passes = 3
    shadow_size = 15
    shadow_boost = 3
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = -45, -175
    halign = right
    valign = top
    shadow_passes = 3
    shadow_size = 15
    shadow_boost = 3
}
label {
    monitor =
    text = cmd[update:5000] /home/dln/.dotfiles/bin/battery_lock  # refresh every 5s
    font_size = 18
    # font_family = JetBrainsMono Nerd Font
    font_family = $font
    position = -25, 25
    halign = right
    valign = bottom
    shadow_passes = 3
    shadow_size = 15
    shadow_boost = 3
}

label {
    monitor =
    text = $LAYOUT[se]
    font_size = 24
    onclick = hyprctl switchxkblayout all next

    position = 250, -20
    halign = center
    valign = center
    shadow_passes = 5
}
