#preload = /home/dln/Wallpapers/ign_Big_macOS_Sur-8.jpg
#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
#wallpaper = ,/home/dln/Wallpapers/ign_Big_macOS_Sur-8.jpg
#if more than one monitor in use, can load a 2nd image
# wallpaper = monitor2,/path/to/next_image.png
# .. more monitors
#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
ipc = on

wallpaper {
    monitor =
    # path = /home/dln/Wallpapers/1r1kk9qi00961.png
    path = /home/dln/Wallpapers/
    fit_mode = cover
    timeout = 3600
}
